/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the edi
 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sayedur;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.*;
import java.util.Collections;
/**
 *
 * @author User
 */
public class Sayedur extends javax.swing.JFrame {

    public int oparator,count=0,j;
    static int i=0;
     String  test;
     static String[] strArray = new String[100];
     //String ch[] = new String[6] ;
     //Scanner sc = new Scanner(System.in);
    
    /**
     * Creates new form NewJFrame
     */
    public Sayedur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("6");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("4");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("9");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("7");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("+");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("*");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("-");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addComponent(jButton6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton4)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10)
                            .addComponent(jButton11)
                            .addComponent(jButton12))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton10))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton4)
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton12))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
         test = jButton1.getLabel();
              
          strArray[i]=test;
          
          /*for(k=0;k<=i;k++)
          {
           jTextField1.setText(strArray[k]+);
          }*/
          String valueToBeInserted="";

            for( j=0;j<= i;j++)
            {
              valueToBeInserted=valueToBeInserted + " " + strArray[j];
                 //System.out.print("array string"+valueToBeInserted);
             }

             jTextField1.setText(valueToBeInserted);


            // jTextField1.setText(jTextField1.getText()+strArray[i]);
               
             oparator=0;   
               i++; 
    }                                           

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
        test = jButton1.getLabel();
               
           strArray[i]=test;
          
          /*for(k=0;k<=i;k++)
          {
           jTextField1.setText(strArray[k]+);
          }*/
          String valueToBeInserted="";

            for( j=0;j<= i;j++)
            {
              valueToBeInserted=valueToBeInserted + " " + strArray[j];
                 //System.out.print("array string"+valueToBeInserted);
             }

             jTextField1.setText(valueToBeInserted);

             //jTextField1.setText(jTextField1.getText()+strArray[i]);
               
             oparator=0;   
               i++; 
              
    }                                        

    
        
                            
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         test = jButton3.getLabel();
         
           strArray[i]=test;
          
          /*for(k=0;k<=i;k++)
          {
           jTextField1.setText(strArray[k]+);
          }*/
          String valueToBeInserted="";

            for( j=0;j<= i;j++)
            {
              valueToBeInserted=valueToBeInserted + " " + strArray[j];
                // System.out.print("array string"+valueToBeInserted);
             }

             jTextField1.setText(valueToBeInserted);

             //jTextField1.setText(jTextField1.getText()+strArray[i]);
               
             oparator=0;   
               i++; 
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         test = jButton2.getLabel();
        
            strArray[i]=test;
          
          /*for(k=0;k<=i;k++)
          {
           jTextField1.setText(strArray[k]+);
          }*/
          String valueToBeInserted="";

            for( j=0;j<= i;j++)
            {
              valueToBeInserted=valueToBeInserted + " " + strArray[j];
                 //System.out.print("array string"+valueToBeInserted);
             }

             jTextField1.setText(valueToBeInserted);

             //jTextField1.setText(jTextField1.getText()+strArray[i]);
               
             oparator=0;   
               i++; 
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
                                                 
        // TODO add your handling code here:
         test = jButton6.getLabel();
           strArray[i]=test;
          
          /*for(k=0;k<=i;k++)
          {
           jTextField1.setText(strArray[k]+);
          }*/
          String valueToBeInserted="";

            for( j=0;j<= i;j++)
            {
              valueToBeInserted=valueToBeInserted + " " + strArray[j];
                 //System.out.print("array string"+valueToBeInserted);
             }

             jTextField1.setText(valueToBeInserted);
             

             //jTextField1.setText(jTextField1.getText()+strArray[i]);
               
             oparator=0;   
               i++; 
          
    
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        test = jButton5.getLabel();
         
          strArray[i]=test;
          
          /*for(k=0;k<=i;k++)
          {
           jTextField1.setText(strArray[k]+);
          }*/
          String valueToBeInserted="";

            for( j=0;j<= i;j++)
            {
              valueToBeInserted=valueToBeInserted + " " + strArray[j];
                 //System.out.print("array string"+valueToBeInserted);
             }

             jTextField1.setText(valueToBeInserted);

             //jTextField1.setText(jTextField1.getText()+strArray[i]);
               
             oparator=0;   
               i++; 
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        test = jButton4.getLabel();
     
         
          strArray[i]=test;
          
          /*for(k=0;k<=i;k++)
          {
           jTextField1.setText(strArray[k]+);
          }*/
          String valueToBeInserted="";

            for( j=0;j<= i;j++)
            {
              valueToBeInserted=valueToBeInserted + " " + strArray[j];
                 //System.out.print("array string"+valueToBeInserted);
             }

             jTextField1.setText(valueToBeInserted);

             //jTextField1.setText(jTextField1.getText()+strArray[i]);
               
             oparator=0;   
               i++; 
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        test = jButton9.getLabel();
            
          strArray[i]=test;
          
          /*for(k=0;k<=i;k++)
          {
           jTextField1.setText(strArray[k]+);
          }*/
          String valueToBeInserted="";

            for( j=0;j<= i;j++)
            {
              valueToBeInserted=valueToBeInserted + " " + strArray[j];
                 //System.out.print("array string"+valueToBeInserted);
             }

             jTextField1.setText(valueToBeInserted);

             //jTextField1.setText(jTextField1.getText()+strArray[i]);
               
             oparator=0;   
               i++; 
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        test = jButton8.getLabel();
             
          strArray[i]=test;
          
          /*for(k=0;k<=i;k++)
          {
           jTextField1.setText(strArray[k]+);
          }*/
          String valueToBeInserted="";

            for( j=0;j<= i;j++)
            {
              valueToBeInserted=valueToBeInserted + " " + strArray[j];
              
                 //System.out.print("array string"+valueToBeInserted);
             }

             jTextField1.setText(valueToBeInserted);

             //jTextField1.setText(jTextField1.getText()+strArray[i]);
               
             oparator=0;   
               i++; 
          
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        test = jButton7.getLabel();
              
          strArray[i]=test;
          
          /*for(k=0;k<=i;k++)
          {
           jTextField1.setText(strArray[k]+);
          }*/
          String valueToBeInserted="";

            for( j=0;j<= i;j++)
            {
              valueToBeInserted=valueToBeInserted + " " + strArray[j];
              //System.out.print("array string"+valueToBeInserted);
             }

             jTextField1.setText(valueToBeInserted);

             //jTextField1.setText(jTextField1.getText()+strArray[i]);
               
             oparator=0;   
               i++; 
    }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        test = jButton10.getLabel();
        
            if (oparator==1)
                     
                
                strArray[i-1]=test;
            
             
                else
            
                   strArray[i]=test; 
              
             if(oparator==1) 
             {
                
            String valueToBeInserted="";

            for( j=0;j<i;j++)
            {
              valueToBeInserted=valueToBeInserted + " " + strArray[j];
             }

             jTextField1.setText(valueToBeInserted);
               //System.out.println("total string " +valueToBeInserted);
               //System.out.println("oparator shows i-2 " +strArray[i-2]);
            }
            
            else if(oparator==0) 
            {
                               
           String valueToBeInserted="";

            for( j=0;j<= i;j++)
            {
              valueToBeInserted=valueToBeInserted + " " + strArray[j];
             }

             jTextField1.setText(valueToBeInserted);
             //System.out.println("total string " +valueToBeInserted);
              i++; 
            }
          
          
             oparator=1;   
             
            
                       
    }
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        test = jButton11.getLabel();
       
         if (oparator==1)
                     
                
                strArray[i-1]=test;
            
             
                else
            
                   strArray[i]=test; 
              
             if(oparator==1) 
             {
                
            String valueToBeInserted="";

            for( j=0;j<i;j++)
            {
              valueToBeInserted=valueToBeInserted + " " + strArray[j];
             }

             jTextField1.setText(valueToBeInserted);
               //System.out.println("total string " +valueToBeInserted);
               //System.out.println("oparator shows i-2 " +strArray[i-2]);
            }
            
            else if(oparator==0) 
            {
                               
           String valueToBeInserted="";

            for( j=0;j<= i;j++)
            {
              valueToBeInserted=valueToBeInserted + " " + strArray[j];
             }

             jTextField1.setText(valueToBeInserted);
             //System.out.println("total string " +valueToBeInserted);
              i++; 
        
           } 
             oparator=1;
    }


    
    
    
     private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        test = jButton12.getLabel();
       
         if (oparator==1)
                     
                
                strArray[i-1]=test;
            
             
                else
            
                   strArray[i]=test; 
              
             if(oparator==1) 
             {
                
            String valueToBeInserted="";

            for( j=0;j<i;j++)
            {
              valueToBeInserted=valueToBeInserted + " " + strArray[j];
              
               //System.out.println("oparator total string " + strArray[j]);
             }

             jTextField1.setText(valueToBeInserted);
               //System.out.println("total string " +valueToBeInserted);
               //System.out.println("oparator shows i-2 " +strArray[i-2]);
            }
            
            else if(oparator==0) 
            {
                               
           String valueToBeInserted="";

            for( j=0;j<= i;j++)
            {
              valueToBeInserted=valueToBeInserted + " " + strArray[j];
                // System.out.print("array string"+valueToBeInserted);
              
              //System.out.println("no oparator total string " + strArray[j]);
              
             }

             jTextField1.setText(valueToBeInserted);
             //System.out.println("total string " +valueToBeInserted);
              i++; 
        
           } 
             oparator=1;           
             
             
    }

     

    
    public static void main(String args[]) {
        
        
        int k;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sayedur().setVisible(true);
            }
        });
        
        for( k=0;k<=i;k++)
            {
              
            
               System.out.print("total string " + strArray[k]);
             }
        
    }


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}

